POST http://localhost:8080/api/solve
Content-Type: application/json

{
  "first": [ 
    { "capacity": 47, "current": 0}, 
    { "capacity": 19, "current": 0} , 
    { "capacity": 13, "current": 0} ,
    { "capacity": 7, "current": 0} 
  ],
  "second": [
    { "capacity": 47, "current": 43}, 
    { "capacity": 19, "current": 0} , 
    { "capacity": 13, "current": 0} ,
    { "capacity": 7, "current": 0} 
  ]
}
